config/routes.rb
TraApi::Application.routes.draw do
  namespace :api, defaults: { format: 'json' } do
    namespace :v1 do
      get "train/:id" => "train#show"
      get "station/:date/:dep/:arr" => "station#show"
      get "station_info" => "station_info#show"
    end
  end
  devise_for :users
  get 'document' => 'high_voltage/pages#show', :id => 'document'
  root :to => 'high_voltage/pages#show', :id => 'welcome'

end

app/models/car_class.rb
class CarClass < ActiveRecord::Base
end

app/models/setting.rb
class Setting < Settingslogic
  source "#{Rails.root}/config/config.yml"
  namespace Rails.env
end

app/models/station.rb
class Station < ActiveRecord::Base
  belongs_to :time_info
end

app/models/tai_train_list.rb
class TaiTrainList < ActiveRecord::Base
  has_many :train_info
end

app/models/time_info.rb
class TimeInfo < ActiveRecord::Base
  belongs_to :train_info
  has_one :station_info, :class_name => "Station", :foreign_key => "no", :primary_key => "station"
end

app/models/train_info.rb
class TrainInfo < ActiveRecord::Base
  belongs_to :tai_train_list
  has_many :time_info
end

app/models/user.rb
class User < ActiveRecord::Base
  before_create :generate_api_key
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  private
  def generate_api_key
    begin
      self.api_key = SecureRandom.hex
    end while self.class.exists?(api_key: api_key)
  end
end

app/controllers/api/v1/station_controller.rb
class Api::V1::StationController < ApplicationController
  before_filter :restrict_access

  respond_to :json

  def show
    #trains = TrainInfo.where("train_infos.car_class < 1110 and (select count(time_infos.id) from time_infos inner join stations on stations.no=time_infos.station where time_infos.train_date=? and time_infos.train_info_id=train_infos.id and (stations.ticket_no=? or stations.ticket_no=?)) = 2", params[:date], params[:dep], params[:arr])
    sql_string = <<SQL
select 
trains.id,
trains.train_date, 
trains.train, 
trains.car_class,
from_info.dep_time,
to_info.arr_time
from train_infos as trains
join time_infos as from_info on from_info.train_info_id=trains.id
join stations as from_station on from_station.no=from_info.station
join time_infos as to_info on to_info.train_info_id=trains.id
join stations as to_station on to_station.no=to_info.station
where trains.train_date='#{params[:date]}' and from_station.ticket_no='#{params[:dep]}' and to_station.ticket_no='#{params[:arr]}' and (to_info.order - from_info.order > 0)
order by from_info.dep_time;
SQL
    trains = TrainInfo.find_by_sql(sql_string)
    render :json => trains
  end
end

app/controllers/api/v1/station_info_controller.rb
class Api::V1::StationInfoController < ApplicationController
  before_filter :restrict_access

  respond_to :json

  def show
    stations = Station.select("ticket_no as id, name as value").where("ticket_no != ''").order("ticket_no ASC")
    hash_stations = {}
    stations.each {|s| hash_stations["%03d-%s"% [s.id, s.value]] = "%03d"% s.id}
    render :json => hash_stations
  end
end

app/controllers/api/v1/train_controller.rb
class Api::V1::TrainController < ApplicationController
  before_filter :restrict_access

  respond_to :json

  def show
    train = TrainInfo.where(train: params[:id]).first
    render :json => train.to_json(:include => :time_info)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  private
  def restrict_access
    api_key = User.find_by(:api_key => params[:api_key])
    head :unauthorized unless api_key
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TraApi</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<nav class="navbar navbar-default" role="navigation">
  <!-- Brand and toggle get grouped for better mobile display -->
  <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <%= link_to Setting.app_name, root_path, :class => "navbar-brand" %>
  </div>

  <!-- Collect the nav links, forms, and other content for toggling -->
  <div class="collapse navbar-collapse">
    <ul class="nav navbar-nav">
      <li><%= link_to 'Document', document_path %></li>
    </ul>
    <ul class="nav navbar-nav navbar-right">
      <% if user_signed_in? %>
        <li class="dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown"><%= current_user.email %><b class="caret"></b></a>
          <ul class="dropdown-menu">
            <li><%= link_to "Account", edit_user_registration_path %></li>
            <li><%= link_to "Sign out", destroy_user_session_path, :method => :delete %></li>
          </ul>
        </li>
      <% else %>
        <li><%= link_to "Sign in", new_user_session_path %></li>
      <% end %>
    </ul>
  </div><!-- /.navbar-collapse -->
</nav>

<%= yield %>

</body>
</html>

app/views/pages/document.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-3">
      <div class="hidden-print" role="complementary">
        <ul class="nav">
          <li><a href="#getting-started">Getting started</a></li>
          <li>
            <a href="#api-v1">API V1</a>
            <ul class="nav">
              <li><a href="#api-v1-train">Train</a></li>
              <li><a href="#api-v1-station_info">Station Information</a></li>
              <li><a href="#api-v1-station">Station</a></li>
            </ul>
          </li>
        </ul>
      </div>
    </div>
    <div class="col-md-9" role="main">
      <!-- Getting started -->
      <div>
        <div class="page-header">
          <h1 id="getting-started">Getting started</h1>
        </div>
        <p class="lead">TBD</p>
      </div>

      <!-- API v1 -->
      <div>
        <div class="page-header">
          <h1 id="api-v1">API V1</h1>
        </div>
        <p class="lead">TBD</p>
        <h2 id="api-v1-train">Train</h2>
        <p>
          <p>利用車次查詢該車次資料。</p>
          <h3>Resource URL</h3>
          <p>/api/v1/train/:train_no</p>
          <h3>Parameters</h3>
          <h4>train_no</h4>
          <p>車次</p>
        </p>
        <h2 id="api-v1-station_info">Station Information</h2>
        <p>
          <p>查詢車站資訊</p>
          <h3>Resource URL</h3>
          <p>/api/v1/station_info</p>
        </p>
        <h2 id="api-v1-station">Station</h2>
        <p>
          <p>利用車站查詢班次</p>
          <h3>Resource URL</h3>
          <p>/api/v1/station/:train_date/:depart/:arrive</p>
          <h3>Parameters</h3>
          <h4>train_date</h4>
          <p>乘車日期。格式 YYYYMMDD</p>
          <h4>depart</h4>
          <p>出發車站</p>
          <h4>arrive</h4>
          <p>到達車站</p>
        </p>
      </div>
    </div>
  </div>
</div>

app/views/pages/welcome.html.erb
<div class="row">
  <div class="col-md-8 col-md-offset-2">
    <div class="jumbotron">
      <div class="container">
        <h1>台鐵 API</h1>
        <p>提供簡易的 API 方便查詢台鐵火車班次，並使用 JSON 格式輕易的與程式整合。</p>
        <p><%= link_to 'Learn more', document_path, :class => "btn btn-primary btn-lg" %></p>
      </div>
    </div>
  </div>
</div>

app/views/users/shared/_links.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Sign in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>